### PR TITLE
Feature breadcrumbs vanessa

### PR DESCRIPTION
**Pull request by VannaSky**
I added some breadcrumbs to all pages for the "vision of BSAG Intranet" for Mr Cordes =)

Breadcrumbs are missing for IdeaManagement and MyProfile: I have to check with the authors how they constructed their classes. 

That's why I will set this request back to draft after creating the request. But who like to check, can see the breadcrums.

### CODE REVIEW

**Comment by VannaSky** [comment]
Added the breadcrumbs to the missing files. 
Can be reviewed and merged now :-)

**Comment by sabrine-gamdou** [comment]
Looks good, all pages have the breadcrumbs, except the LibraryView. Would you change it in another pull request?
image

**Review by sabrine-gamdou — APPROVED** [review]
Looks good :)

**Comment by anastasiya-jh** [comment]
Looks also good for me, but the breadcrumbs are not always implemented the same way. Sometimes its in a setData() method or in the constructor. The positions also differ a lot. Sometimes u implemented it at the start of constructor and there are examples in which u implemented it at the end. Due to time I guess we will not have the time to change that, but I just wanted to tell you :)

**Pull request merged**
