### PR TITLE
Feature navbar monika

### PR DESCRIPTION
**Pull request by MoMa666**
Kompletter Code in mainView abgeändert und ersetzt. Horizontale Navbar hinzugefügt. Layouts erstellt und die Div Boxen sowie sideBar damit positioniert. Style via Figma Code ersetzt/angepasst.

### CODE REVIEW

**Comment by sabrine-gamdou** [comment]
Everything functional, great job! The website is however not responsive

**Review by anastasiya-jh — APPROVED** [review]
Reviewed and Approved. Some styling problems were already discussed and written down. Not responsive yet!

**Review by sabrine-gamdou — APPROVED** [review]
Layout very similar to what we need, to make it responsive is the next step 👍

**Review by sabrine-gamdou — APPROVED** [review]
Reviewed

**Review by sabrine-gamdou — APPROVED** [review]
Conflicts resolved

**Review by anastasiya-jh — APPROVED** [review]
Reviewed and Approved. Everything seems to be fine. Issues were communicated.

**Pull request merged**
